{
  services.zapret = {
    enable = true;
    params = [
      "--wf-tcp=80,443,2053,2083,2087,2096,8443"
      "--wf-udp=443,19294-19344,50000-50100"

      "--filter-udp=443"
      "--dpi-desync=fake"
      "--dpi-desync-repeats=6"
      "--new"

      "--filter-udp=19294-19344,50000-50100"
      "--filter-l7=discord,stun"
      "--dpi-desync=fake"
      "--dpi-desync-repeats=6"
      "--new"

      "--filter-tcp=2053,2083,2087,2096,8443"
      "--hostlist-domains=discord.media"
      "--dpi-desync=fake"
      "--dpi-desync-fake-tls-mod=none"
      "--dpi-desync-repeats=6"
      "--dpi-desync-fooling=badseq"
      "--dpi-desync-badseq-increment=2"
      "--new"

      "--filter-tcp=443"
      "--ip-id=zero"
      "--dpi-desync=fake"
      "--dpi-desync-fake-tls-mod=none"
      "--dpi-desync-repeats=6"
      "--dpi-desync-fooling=badseq"
      "--dpi-desync-badseq-increment=2"
      "--new"

      "--filter-tcp=80,443"
      "--dpi-desync=fake"
      "--dpi-desync-fake-tls-mod=none"
      "--dpi-desync-repeats=6"
      "--dpi-desync-fooling=badseq"
      "--dpi-desync-badseq-increment=2"
      "--new"

      "--filter-udp=443"
      "--dpi-desync=fake"
      "--dpi-desync-repeats=6"
      "--new"

      "--filter-tcp=80,443"
      "--dpi-desync=fake"
      "--dpi-desync-fake-tls-mod=none"
      "--dpi-desync-repeats=6"
      "--dpi-desync-fooling=badseq"
      "--dpi-desync-badseq-increment=2"
      "--new"

      "--filter-udp"
      "--dpi-desync=fake"
      "--dpi-desync-repeats=12"
      "--dpi-desync-any-protocol=1"
      "--dpi-desync-cutoff=n2"
    ];
    whitelist = [
      "cloudflare-ech.com"
      "encryptedsni.com"
      "cloudflareaccess.com"
      "cloudflareapps.com"
      "cloudflarebolt.com"
      "cloudflareclient.com"
      "cloudflareinsights.com"
      "cloudflareok.com"
      "cloudflarepartners.com"
      "cloudflareportal.com"
      "cloudflarepreview.com"
      "cloudflareresolve.com"
      "cloudflaressl.com"
      "cloudflarestatus.com"
      "cloudflarestorage.com"
      "cloudflarestream.com"
      "cloudflaretest.com"
      "cloudfront.net"
      "dis.gd"
      "discord-attachments-uploads-prd.storage.googleapis.com"
      "discord.app"
      "discord.co"
      "discord.com"
      "discord.design"
      "discord.dev"
      "discord.gift"
      "discord.gifts"
      "discord.gg"
      "discord.media"
      "discord.new"
      "discord.store"
      "discord.status"
      "discord-activities.com"
      "discordactivities.com"
      "discordapp.com"
      "discordapp.net"
      "discordcdn.com"
      "discordmerch.com"
      "discordpartygames.com"
      "discordsays.com"
      "discordsez.com"
      "discordstatus.com"
      "frankerfacez.com"
      "ffzap.com"
      "betterttv.net"
      "7tv.app"
      "7tv.io"
      "localizeapi.com"
      "klipy.com"
    ];
  };
}
